### ISSUE TITLE
Need jdk 11 version

### ISSUE THREAD

**Issue by wildone** [aem-design/docker-aem#13]
## Feature Request

Need to create a version that uses JDK 11, this should result in a new TAG that will allow pilling JDK8 and JDK11 images.

**Comment by zerowebcorp** [comment]
Hi, great work. Is there a way to use OpenJDK instead of the Java from Oracle? Not many people can use Oracle JDK after they changed their T&S last year

**Comment by wildone** [comment]
done

**Comment by wildone** [comment]
> Hi, great work. Is there a way to use OpenJDK instead of the Java from Oracle? Not many people can use Oracle JDK after they changed their T&S last year

Adobe does not support OpenJDK, when you develop AEM you can use OracleJDK as its covered by their license.

**Comment by wildone** [comment]
@getvivekv ^^^
