### ISSUE TITLE
Can't start AEM with latest or 6.5.0 image on mac m1

### ISSUE THREAD

**Issue by mkovacek** [aem-design/docker-aem#14]
## Bug Report

**Current Behavior**

I'm trying to prepare a local dev environment following instructions in the readme file, but during running, the docker image throws errors and the image is not up and running.
[log](https://gist.github.com/mkovacek/2cace0bd245c90af5e2ec681a639e2a7) 

I tried next commands:
`docker run --platform linux/amd64 --name author -e "AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,dev" -p4502:8080 -d -p34502:58242 aemdesign/aem`

`docker run --platform linux/amd64 --name author -e "AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,dev" -p4502:8080 -d -p34502:58242 aemdesign/aem:6.5.0`

`docker run --name author -e "AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,dev" -p4502:8080 -d -p34502:58242 aemdesign/aem`

`docker run  --name author -e "AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,dev" -p4502:8080 -d -p34502:58242 aemdesign/aem:6.5.0`

**Expected behavior/code**
I'm expecting to have up and running AEM in the docker container.

**Environment**
- AEM 6.5.0 / also tried lastest 6.5.10.0-jdk11
- JDK 1.8 and JDK 11
- MacBook pro M1 PRO
- macOS Monterey

**Comment by wildone** [comment]
Hope you tried one of the ARM images https://github.com/aem-design/docker-aem/tree/6.5.11.0-jdk11-arm

**Comment by mkovacek** [comment]
Huh that was long time ago :D
Not relevant anymore
