### ISSUE TITLE
Create 6.2.0 and 6.2.0-bundle versions

### ISSUE THREAD

**Issue by wildone** [aem-design/docker-aem#5]
## Feature Request

Need 6.2.0 and 6.2.0-bundle images so that they can be used for upgrades.

**Comment by PreDer** [comment]
I Would be pleased to see a image with 6.2 :)

**Comment by wildone** [comment]
ok here it comes.

**Comment by wildone** [comment]
@PreDer try this.

`docker run --name author620 -e "TZ=Australia/Sydney" -e "AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,forms,localdev" -e "AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=58242,suspend=n" -p4522:8080 -p30323:58242 -d aemdesign/aem:6.2.0`

**Comment by wildone** [comment]
@PreDer do you have any of the bundle packages?

**Comment by PreDer** [comment]
Which bundles do you mean exactly?
